"""
viewer.py
─────────
Interactive Web Dashboard for NazarGeo.
Point-and-click map to view building images captured by the vehicle.
Run this using: streamlit run viewer.py
"""

import os
import json
import pandas as pd
import streamlit as st
import folium
from streamlit_folium import st_folium
from PIL import Image

# ─── Configuration & Pathing ───
st.set_page_config(page_title="NazarGeo Building Explorer", layout="wide")

# Automatically find the exact path to your 'n3' folder
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# Construct absolute paths to your data folders
SUMMARY_PATH = os.path.join(BASE_DIR, "out", "summary", "batch_summary.json")
STABLE_DIR   = os.path.join(BASE_DIR, "out", "stable_json")
VIS_DIR      = os.path.join(BASE_DIR, "out", "perceive_vis")

@st.cache_data
def load_data():
    """
    Parses the batch_summary.json generated by run_batch.py and
    the individual stable_json files to gather image paths.
    """
    if not os.path.exists(SUMMARY_PATH):
        return pd.DataFrame()

    with open(SUMMARY_PATH, "r") as f:
        data = json.load(f)
    
    summary_data = data.get("summary", {})
    per_track = summary_data.get("per_track", [])
    
    if not per_track:
        return pd.DataFrame()

    records = []
    # Loop through every building track the Kalman filter found
    for track in per_track:
        # Convert track_id to string to avoid matching errors
        track_id = str(track.get("track_id"))
        
        best_frame_data = None
        highest_score = -1

        # Scan the stable_json folder to find the best frame for this track
        if os.path.exists(STABLE_DIR):
            for filename in os.listdir(STABLE_DIR):
                if filename.endswith(".json"):
                    with open(os.path.join(STABLE_DIR, filename), "r") as jf:
                        frame_data = json.load(jf)
                        frame_track_id = str(frame_data.get("stable", {}).get("track_id"))
                        
                        if frame_track_id == track_id:
                            score = frame_data.get("raw_match", {}).get("score", 0)
                            if score > highest_score:
                                highest_score = score
                                best_frame_data = frame_data

        if best_frame_data:
            frame_id = best_frame_data["frame_id"]
            vis_path = best_frame_data.get("vis")
            
            # If vis path is missing, construct the absolute path manually
            if not vis_path or not os.path.exists(vis_path):
                vis_path = os.path.join(VIS_DIR, f"frame_{frame_id:06d}_perceive_vis.jpg")

            records.append({
                "track_id": track_id,
                "lat": track["mean_lat"],
                "lon": track["mean_lon"],
                "frames_tracked": track["frames"],
                "mean_score": track["mean_raw_score"],
                "best_frame_id": frame_id,
                "best_score": highest_score,
                "vis_path": vis_path,
                "depth_m": best_frame_data.get("depth_m", "N/A")
            })

    return pd.DataFrame(records)

# ─── UI Layout ───
st.title("🌍 NazarGeo: Street-View Building Explorer")
st.markdown("Interactive map generated from vehicle LiDAR & Camera telemetry. Click a building pin to view the captured frame.")

df = load_data()

if df.empty:
    st.error(f"Could not load tracking data. \n\nLooking for file at: `{SUMMARY_PATH}` \n\nMake sure you have run the pipeline!")
    st.stop()

# Create two columns: Map on the left (70%), Details on the right (30%)
col1, col2 = st.columns([7, 3])

with col1:
    # Center map on the average coordinates of all tracked buildings
    map_center = [df["lat"].mean(), df["lon"].mean()]
    m = folium.Map(location=map_center, zoom_start=18, tiles="CartoDB positron")

    # Add a marker for every building tracked by the Kalman filter
    for idx, row in df.iterrows():
        folium.CircleMarker(
            location=[row["lat"], row["lon"]],
            radius=8,
            color="#FF4B4B",       # Streamlit red
            fill=True,
            fill_color="#FF4B4B",
            fill_opacity=0.8,
            tooltip=f"Track ID: {row['track_id']} (Score: {row['mean_score']:.1f})",
            popup=str(row["track_id"]) # The popup value is what we capture on click
        ).add_to(m)

    # Render the map and capture user clicks
    map_data = st_folium(m, width=800, height=600, returned_objects=["last_object_clicked_popup"])

with col2:
    st.subheader("📸 Building Inspector")
    
    # Check if a user clicked a pin on the map
    clicked_track_id = map_data.get("last_object_clicked_popup")
    
    if clicked_track_id:
        # Fetch the dataframe row for the clicked pin
        bldg_data = df[df["track_id"] == clicked_track_id].iloc[0]
        
        st.success(f"**Track ID:** {bldg_data['track_id']}")
        st.write(f"📍 **GPS Coords:** {bldg_data['lat']:.6f}, {bldg_data['lon']:.6f}")
        st.write(f"📏 **LiDAR Depth:** {bldg_data['depth_m']} meters")
        st.write(f"🎯 **Best Match Score:** {bldg_data['best_score']:.1f}/100")
        st.write(f"🎥 **Captured in Frame:** #{bldg_data['best_frame_id']}")

        # Attempt to show the image
        img_path = bldg_data["vis_path"]
        
        if pd.notna(img_path) and os.path.exists(img_path):
            image = Image.open(img_path)
            st.image(image, caption=f"Vehicle View (Frame {bldg_data['best_frame_id']})", use_container_width=True)
        else:
            # Fallback if the specific perceived visualization is missing
            st.warning(f"Visualization image not found at:\n`{img_path}`")
    else:
        st.info("👈 Click a red marker on the map to view the street-level image.")